import type { NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const videoRef = useRef<HTMLVideoElement>(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"min-h-screen"}>
        <video className="relative" ref={videoRef} loop autoPlay muted>
          <source src="videos/mainVideo.mp4"></source>
        </video>
        <div className="absolute top-2/4 left-2/4 -translate-x-2/4 -translate-y-2/4">
          <div className="text-center">
            <p className="text-white text-5xl">The Forest</p>
            <p className="text-white text-2xl  mt-1">with Stranger</p>
            <button className="bg-gradient-to-r from-green-200 to-green-700 hover:from-pink-500 hover:to-yellow-500 delay-100 mt-4 px-4 py-2 ">
              <span className="text-white font-bold">JOIN</span>
            </button>
          </div>
        </div>
        {
          //main viedo
        }
      </main>
    </div>
  );
};

export default Home;
